export enum PhysicalActivity {
  NO_EXERCISE = 'NO_EXERCISE',
  LIGHT_EXERCISE = 'LIGHT_EXERCISE',
  MODERATE_EXERCISE = 'MODERATE_EXERCISE',
  HARD_EXERCISE = 'HARD_EXERCISE',
  PROFESSIONAL_ATHLETE = 'PROFESSIONAL_ATHLETE'
}
