export enum ProductType {
  PROTEIN = 'PROTEIN',
  VEGETABLES = 'VEGETABLES',
  FRUITS = 'FRUITS',
  GRAINS = 'GRAINS',
  DAIRY = 'DAIRY',
  SWEETS = 'SWEETS',
  OTHERS = 'OTHERS',
  MEAL = 'MEAL',
  DRINK = 'DRINK',
  WATER = 'WATER'
}
